<?php
// +----------------------------------------------------------------------
// | Login 登录路由控制器
// +----------------------------------------------------------------------

namespace app\jiajum\controller;

use app\common\controller\JiajumBase;

class Login extends JiajumBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户登录界面
     */
    public function index()
    {
        $u_userInfo = session('u_userInfo');
        if (!empty($u_userInfo)&&!empty($u_userInfo['id'])) {
            $this->redirect(url('jiajum/user/index',[],''));
        }
        //TDK的title
        $head = "登录-齐装家具网上商城";
        $this->assign('head', $head);
        return $this->fetch();
    }


    /**
     * 用户登录接口
     * POST方式
     * @param [string] name 注册时手机号码
     * @param [string] password 密码
     * @return [json]
     */
    public function login()
    {
        if (!$this->request->isPost()){
            $this->_empty();
        }
        $data['user'] = strtolower(input('post.name'));
        $data['pass'] = input('post.password');

        $errorMsg = $this->validate($data,'User.login');
        if(true !== $errorMsg){
            // 验证失败 输出错误信息
            return json(['status'=>0 ,'info'=>$errorMsg]);
        }
        $user = model("User")->findUserInfoByUser($data["user"]);

        if(!empty($user)){
            if($user["pass"] == md5($data["pass"])){
                //更新登陆时间
                $flag = model('User')->edtiUserInfo($user["id"],["login_time"=> time()]);
                if ($flag === false){
                    return json(["data"=>"","info"=>"登录失败,请稍后重试" ,"status"=>0]);
                }
                //记录登录日志
                $this->saveLoginLog($user['name'],$user["id"]);
                //设置用户session信息
                $this->setUserSession($user);
                return json(["data"=>"","info"=>"登录成功" ,"status"=>1]);
            }else{
                return json(["data"=>"","info"=>"用户帐号/密码错误" ,"status"=>0]);
            }
        }else{
            return json(["data"=>"","info"=>"用户帐号/密码错误" ,"status"=>0]);
        }
    }

    /**
     * 记录登录日志
     * @param $name
     * @param $id
     */
    protected function saveLoginLog($name,$id)
    {
        $app = new \Util\App();
        //记录日志
        $data['username'] = $name;
        $data['userid'] = $id;
        $data['ip'] = $app->get_client_ip();
        $data['user_agent'] = $_SERVER["HTTP_USER_AGENT"];
        $data['info'] = '用户登录成功';
        $data['time'] = date("Y-m-d H:i:s");
        $data['action'] = $this->request->controller()."/".$this->request->action();
        model("LogUser")->addLog($data);
    }

    /**
     * 设置用户session信息
     * @param [array]$user 用户信息
     */
    protected function setUserSession($user)
    {
        switch ($user["classid"])
        {
            //普通用户
            case "1":
            case "2":
            //企业用户
            case '3':
                session('u_userInfo',[
                    "id"=>$user["id"],
                    "name"=>$user["name"],
                    "user"=>$user["user"],
                    "cs"=>$user["cs"],
                    "qx"=>$user["qx"],
                    "logo"=>$user["logo"],
                    "classid"=>$user["classid"],
                    "bm"=>$user["bm"],
                    "cname"=>$user["cname"],
                    "jc"=>$user["name"],
                    "on"=>$user["on"],
                    'blocked'=>$user['blocked']]);
                break;
            default:
                break;
        }
    }

    //退出操作
    public function loginout()
    {
        //分站域名
        $bm = session('u_userInfo.bm');
        //清除用户session
        cache('Cache:User:ID' . session('u_userInfo.id'),null);
        session('u_userInfo',null);
        if($this->request->isAjax()){
            return json(["info"=>"退出成功","status"=>1]);
        }else{
            if (session('?denyNum')){
                $url = url('jiajum/index/index');
                session('denyNum',null);
            }else{
                session('denyNum',1);
                $referUlr = $this->request->header('referer');
                $url = ($referUlr === $this->request->url(true) || $referUlr ===null)?url('jiajum/index/index'):$this->request->header('referer');
            }
            @header("location:" . $url);
            exit();
        }
    }
}
