<?php
// +----------------------------------------------------------------------
// | Login 注册控制器
// +----------------------------------------------------------------------

namespace app\jiajum\controller;

use app\common\controller\JiajumBase;

class Register extends JiajumBase
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 用户注册界面
     */
    public function index()
    {
        return $this->fetch();
    }

    /**
     * 用户注册接口
     * @param [string] tel 手机号码
     * @param [string] password 密码
     * @param [string] repassword 重复密码
     * @param [int] code 验证码
     * @param [int] checkUser 存在并且值为1代表验证手机是否已经被注册
     * @return [type] [description]
     * @return \think\response\View
     */
    public function register()
    {
        if (!$this->request->isPost()){
            $this->_empty();
        }
        $data['tel'] = strtolower(input('post.tel'));
        $data['pass'] = input('post.password');
        $data['repass'] = input('post.repassword');
        $data['code'] = input('post.code');
        $data['authcode'] = intval(input('post.authcode','0'));
        //验证输入信息
        $errorMsg = $this->validate($data,'User.register');
        if(true !== $errorMsg){
            // 验证失败 输出错误信息
            return json(['status'=>0 ,'info'=>$errorMsg]);
        }
        //验证手机号是否注册
        $valiUser['user'] = $data["tel"];
        //验证用户帐号
        $find = model("User")->checkAccount($valiUser);
        if ($find !== false) {
            return json(["data" => "", "info" => '该手机已被注册', "status" => 0]);
        }

        //验证手机验证码
        $check = checkSafeCode($data);
        if ($check['status'] == 0 ){
            return json($check);
        }
        $addFlag = model("User")->addUserInfo($data);
        if ($addFlag !== false){
            $rel = ["data"=>"","info"=>"注册成功" ,"status"=>1];
        }else{
            $rel = ["data"=>"","info"=>"注册失败,请稍后重试" ,"status"=>0];
        }
        return json($rel);
    }

    /**
     * 用户协议条款界面
     * @return mixed
     */
    public function agreement()
    {
        return $this->fetch();
    }
}
