<?php
namespace app\mobile\controller;

use app\common\controller\MobileCommonBase;
use app\common\model\logic\SupplierLogic;
use app\common\enums\ErrorCode;
use app\common\model\logic\LogLogic;

/**
 * 移动端供应商管理
 * Class Supplier
 * @package app\mobile\controller
 */
class Supplier extends MobileCommonBase
{
    public $company_id;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->company_id = session('userInfo.company_id');
    }
    //供应商管理
    public function index(SupplierLogic $SupplierLogic){
        $post = input('get.');
        $supplier_name = isset($post['gys'])?$post['gys']:'';
        //获取首页列表数据
        $info = $SupplierLogic->getmSupplier($this->company_id,$supplier_name);

        if($this->request->isAjax()){
            return json(['error_code'=>ErrorCode::SUCCESS,'data'=>$info['list'],'page'=>$info['page']]); //成功
        }else{
            $this->assign('list',$info['list']);
            $this->assign('page',$info['page']);
            return $this->fetch();
        }
    }

    //添加 供应商
    public function add(){
        return $this->fetch();
    }

    //编辑 供应商
    public function edit(){
        return $this->fetch();
    }


    //供应商详情
    public function detail(SupplierLogic $SupplierLogic){

        $supplier_id = input('get.id');
        //获取供应商信息
        $info["supplier"] = $SupplierLogic->getSupplierInfo($supplier_id);
        //获取供应商银行信息
        $info["bank"] = $SupplierLogic->getSupplierBankInfo($supplier_id);
        $payType = $SupplierLogic->getPayType();

        $this->assign("payType",$payType);
        $this->assign("info",$info);
        return  $this->fetch();
    }

    //付款方式
    public function payway(){
        return  $this->fetch();
    }

    //删除
    public function del(SupplierLogic $SupplierLogic,LogLogic $LogLogic){
        if($this->request->isAjax()){
            $post = input('post.');
            $supplier_id = $post["sid"];
            $result = $SupplierLogic->delSupplier($supplier_id,$this->company_id);
            if($result){
                //删除日志
                $LogLogic->addLog(2, json_encode($post));
                return json()->data(array('error_code'=>ErrorCode::SUCCESS,'error_msg'=>'删除成功'));
            }else{
                return json()->data(array('error_code'=>ErrorCode::SERVICE_MYSQL_ERROR,'error_msg'=>'删除失败'));
            }
        }


    }


}